Repository Wolven531/simple-cra-app, pull requests merged in 2021-07, with the labels that each got.

#38 Remove api prop
  src/ApiContext.tsx
  src/App/App.tsx
  src/Nav/Nav.tsx
  src/SearchUsersPage/SearchUsersPage.tsx
Labels: approved, refactor

#40 ci: Adds unit test on run
  .github/workflows/pull_requests.yml
Labels: tests

#41 Add unit tests using RTL for ConfigPage
  jest.config.js
  package-lock.json
  package.json
  rtl.setup.js
  src/App/App.test.tsx
  src/App/App.tsx
  src/App/rtl-testing.test.tsx
  src/ConfigPage/ConfigPage.test.tsx
  src/ConfigPage/ConfigPage.tsx
  src/GlobalContext.tsx
  src/HomePage/HomePage.tsx
  src/IconDemo.tsx
  src/Nav/Nav.tsx
  src/PageNotFoundPage/PageNotFoundPage.tsx
  src/SearchUsersPage/SearchUsersPage.test.tsx
  src/SearchUsersPage/SearchUsersPage.tsx
  src/testing-utils.tsx
Labels: refactor, tests

#39 Added loading icon to UserSearch
  package-lock.json
  package.json
  src/LoadingModal/LoadingModal.css
  src/LoadingModal/LoadingModal.test.tsx
  src/LoadingModal/LoadingModal.tsx
  src/SearchUsersPage/SearchUsersPage.css
  src/SearchUsersPage/SearchUsersPage.tsx
Labels: approved, css, feature

#42 Add unit tests for Nav component
  src/ConfigPage/ConfigPage.test.tsx
  src/Nav/Nav.test.tsx
  src/Nav/Nav.tsx
  testing-utils.tsx
Labels: tests

#44 Adding e2e nav tests
  src/Nav/Nav.tsx
  test/cypress.json
  test/cypress/integration/ConfigPage.spec.js
  test/cypress/integration/HomePage.spec.js
  test/cypress/integration/PageNotFound.spec.js
  test/cypress/integration/SearchUserPage.spec.js
  test/cypress/integration/simplePage.spec.js
  tsconfig.json
Labels: approved, tests

#51 Handle user not found
  src/Footer/Footer.css
  src/Footer/Footer.tsx
  src/SearchUsersPage/SearchUsersPage.test.tsx
  src/SearchUsersPage/SearchUsersPage.tsx
  src/services/ApiService.ts
Labels: approved, css, feature, tests

#55 Add display total mastery page
  src/App/App.tsx
  src/MasteryPage/MasteryPage.tsx
  src/SearchUsersPage/SearchUsersPage.tsx
  src/services/ApiService.ts
Labels: approved, css, feature

#58 Add button on search users page #54
  src/SearchUsersPage/SearchUsersPage.tsx
  src/services/ApiService.ts
Labels: approved, css, feature

#56 Add display users
  src/App/App.test.tsx
  src/App/App.tsx
  src/DisplayUsersPage/DisplayUsersPage.css
  src/DisplayUsersPage/DisplayUsersPage.test.tsx
  src/DisplayUsersPage/DisplayUsersPage.tsx
  src/Nav/Nav.test.tsx
  src/Nav/Nav.tsx
  src/index.tsx
  src/services/ApiService.ts
  test/cypress/integration/HomePage.spec.js
  test/cypress/integration/SearchUserPage.spec.js
Labels: approved, refactor

#64 Update theme for buttons 57
  src/ConfigPage/ConfigPage.tsx
  src/SearchUsersPage/SearchUsersPage.tsx
  src/index.css
  src/theme.ts
Labels: css
